"""empty message

Revision ID: 12cd1eb66966
Revises: 37b9b5959c66
Create Date: 2021-02-01 20:07:35.783310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cd1eb66966'
down_revision = '37b9b5959c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('available_from', sa.DateTime(), nullable=True))
    op.add_column('artist', sa.Column('available_to', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'available_to')
    op.drop_column('artist', 'available_from')
    # ### end Alembic commands ###
