"""empty message

Revision ID: 504c5394b292
Revises: 9437c37f9015
Create Date: 2021-01-30 19:53:20.919227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504c5394b292'
down_revision = '9437c37f9015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
