"""empty message

Revision ID: 8259d8d9ba29
Revises: bfca50196e86
Create Date: 2021-02-01 13:35:02.387331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8259d8d9ba29'
down_revision = 'bfca50196e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('listed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'listed_at')
    # ### end Alembic commands ###
