"""empty message

Revision ID: a3111435bbba
Revises: 12cd1eb66966
Create Date: 2021-02-01 20:18:39.977241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3111435bbba'
down_revision = '12cd1eb66966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('lists_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'lists_available')
    # ### end Alembic commands ###
